### ISSUE TITLE
Always turn headers into strings when deserializing them

### ISSUE THREAD

**Issue by brizental** [mozilla/fxa-email-service#108]
Ran into this problem while trying to integrate this service with the auth-server.

We've got some headers that we send as integers (eg. `X-Flow-Begin-Time`), not strings. Since our `Header` type demands a string, that returns an error.

To fix this we would have to implement deserialize for the `Headers` type and always turn anything into a `String` when formatting. I'm thinking just using a `format!("{}", value)` will do it.

**Comment by vladikoff** [comment]
This blocks integration in prod

**Comment by brizental** [comment]
Ended up doing this in the node side for now. https://github.com/mozilla/fxa-auth-server/pull/2494/files#diff-5f7c689c4561f5a22c7a3f9361bc3ef2R8
