### ISSUE TITLE
Allow for setting FXA_EMAIL_MESSAGE_ID_HMAC_KEY

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-email-service#109]
We all love ENV vars, but cannot use it for FXA_EMAIL_MESSAGE_ID_HMAC_KEY at this time

 :(

**Comment by vladikoff** [comment]
`MESSAGE_ID_HMAC_KEY` will also do

**Comment by brizental** [comment]
> MESSAGE_ID_HMAC_KEY will also do

We need the `FXA_EMAIL_` prefix because of https://github.com/mozilla/fxa-email-service/blob/master/src/settings/mod.rs#L133
