### ISSUE TITLE
Is there any conflict between rocket's logging and our data pipeline?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-email-service#111]
Hopefully we can just close this issue because it's not a problem, but I'm opening it to investigate just in case.

Currently, rocket intersperses its own log lines in ours:

```
POST /send application/json:
{"Logger":"fxa_email_service-1.115.0","Type":"fxa_email_service:log","Pid":78877,"Severity":6,"Timestamp":1530622569937387000,"Fields":{"msg":"Request started.","agent":"curl/7.43.0","remoteAddressChain":"127.0.0.1","path":"/send","method":"POST"}}
    => Matched: POST /send application/json
    => Outcome: Success
{"Logger":"fxa_email_service-1.115.0","Type":"fxa_email_service:log","Pid":78877,"Severity":6,"Timestamp":1530622571708633000,"Fields":{"msg":"Request finished succesfully.","agent":"curl/7.43.0","remoteAddressChain":"127.0.0.1","path":"/send","method":"POST","status_msg":"OK","status_code":200}}
    => Response succeeded.
POST /send application/json:
    => Matched: POST /send application/json
{"Logger":"fxa_email_service-1.115.0","Type":"fxa_email_service:log","Pid":78877,"Severity":6,"Timestamp":1530622634974570000,"Fields":{"msg":"Request started.","agent":"curl/7.43.0","remoteAddressChain":"127.0.0.1","path":"/send","method":"POST"}}
    => Outcome: Success
{"Logger":"fxa_email_service-1.115.0","Type":"fxa_email_service:log","Pid":78877,"Severity":6,"Timestamp":1530622636122807000,"Fields":{"msg":"Request finished succesfully.","agent":"curl/7.43.0","remoteAddressChain":"127.0.0.1","path":"/send","method":"POST","status_msg":"OK","status_code":200}}
    => Response succeeded.
```

It's kind of annoying but presumably our data pipeline will be fine with that and will ignore the lines it can't parse, with no adverse effects on the ones it can. But we should double check with someone who knows, just to make sure.

There is a [`log` config setting for rocket](https://api.rocket.rs/rocket/config/index.html#configuration-parameters), which can be set to `normal`, `debug` or `critical`. So if we do want to shut it up a bit, we could set that to `critical`. Maybe that's worth doing regardless of the above anyway, just to reduce log noise.

**Comment by brizental** [comment]
When `ROCKET_ENV` is set to `production`, the `log` config is `critical` by default. Should we change that for the other envs as well?

This is how it looks like:

<img width="745" alt="screen shot 2018-07-03 at 8 45 40 am" src="https://user-images.githubusercontent.com/25176023/42230303-7d6a4b6c-7e9d-11e8-8380-8f47deabe2f5.png">

**Comment by vladikoff** [comment]
from mtg: if it cannot json.parse a line, does it ignore it? Logging 2.0? @jbuck do you know?

**Comment by jbuck** [comment]
Yeah, it'll ignore non-json lines. Is it possible to disable those within the app though?

**Comment by vladikoff** [comment]
> Yeah, it'll ignore non-json lines. Is it possible to disable those within the app though?

@brizental ^

**Comment by brizental** [comment]
> Is it possible to disable those within the app though?

Rocket doesn't have that option as of now. I sent in a PR adding that feature, so we'll have to wait and see if they accept that. Apparently there is a way to hide all logging using `Rocket::custom()` but I couldn't figure out how to do that and just adding a config seems easier and more intuitive.

Link for the PR: https://github.com/SergioBenitez/Rocket/pull/685

**Comment by vladikoff** [comment]
PR merged, need to pin to a SHA while we wait for release...
