### ISSUE TITLE
implement /__version__, /__heartbeat__, /__lbheartbeat__ routes

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-email-service#132]
Semantics in https://github.com/mozilla-services/Dockerflow#containerized-app-requirements

**Comment by vladikoff** [comment]
cc @brizental

**Comment by jrgm** [comment]
So, following the link in point 3 of https://github.com/mozilla-services/Dockerflow#containerized-app-requirements, which is https://github.com/mozilla-services/Dockerflow/blob/master/docs/version_object.md, I see the other FxA servers do not include the `build` uri, and we should correct that in those other repos.

As an example of output of `curl -s 'https://api.accounts.firefox.com/__version__' | python -mjson.tool`:

```
{
    "commit": "67633cc6cd9af2ddc57c53c1e28b1a43166a4a37",
    "source": "https://github.com/mozilla/fxa-auth-server",
    "version": "1.115.1"
}
```

**Comment by pjenvey** [comment]
We've got these in megaphone/pushbox e.g. https://github.com/mozilla-services/pushbox/pull/31

**Comment by vladikoff** [comment]
```rust
content::Json(include_str!("../version.json"))
```

This just looks at the json file, but I'm guessing at some point we would want to get the commit sha dynamically

**Comment by pjenvey** [comment]
for releases, circleci overwrites that version.json just before building:

https://github.com/mozilla/fxa-email-service/blob/master/.circleci/config.yml#L25
