### ISSUE TITLE
Don't tie loglevel to NODE_ENV

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-email-service#138]
In https://github.com/mozilla/fxa-email-service/blob/5d770c33e3664a1bb9f8d05401bd95dcd7375bea/src/settings/mod.rs#L341-L361

In general, we set the default is 'info' log level and the messages sent at that level are appropriate to that level, and if we need to change that for production/staging we can adjust it from the environment.

**Comment by brizental** [comment]
@jrgm do you mean to create a `FXA_EMAIL_LOGLEVEL` environment variable?

**Comment by jrgm** [comment]
@brizental - yes. For example, typical in other repos, the LOG_LEVEL can be changed directly via the environment - https://github.com/mozilla/fxa-auth-server/blob/master/config/index.js#L38-L52
