### ISSUE TITLE
Test message-parsing in the queues process

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-email-service#162]
When we added email headers in #89, notification-parsing in the queues process stopped working. It stopped working because the `Notification` struct was wrong, but we didn't notice because there were no automated tests for the parsing code. When I manually tested it while implementing, everything seemed fine because there were no headers.

The fix for this particular parsing issue is included in #161:

https://github.com/mozilla/fxa-email-service/pull/161/files#diff-d73554e88b8870cc1336cbfba3460e2eR143

But we still don't have any tests to ensure it won't break again in the future. We should add some proper parsing tests, using real data copied from manual testing.

**Comment by philbooth** [comment]
Added this to the Q4 milestone.

**Comment by brizental** [comment]
This was fixed by #188
