### ISSUE TITLE
Allow "empty" settings in environment variables

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-email-service#191]
In the fxa nightly stacks, these values were set in the environment (i.e., "empty" strings).

```
FXA_EMAIL_SENTRY_DSN=
FXA_EMAIL_SOCKETLABS_SERVERID=
FXA_EMAIL_SOCKETLABS_KEY=
```

These cause fxa-email-service to crash with errors such as 
invalid type: string "", expected an integer in the environment
or
invalid value: string "", expected sentry dsn

IMHO, in other server programs, these "empty" environment values would be treated as unset and a program default value would be used.

It's possible to configure `nightly` differently. However, having a different semantics for empty environment variables from what other stacks would have will be a pain.

**Comment by jrgm** [comment]
> It's possible to configure nightly differently. 

Actually, in this case, due to Puppet's immutable hash types and Puppet's odd syntax choices, I would need to write stylish code similar to below for each environment variable that won't accept an empty string as 'not set'. How elegant.

```
  $auth_profile_env_vars = merge({}, $auth_env_vars,
    { 'NEW_RELIC_APP_NAME' => $newrelic_add_config ? 
       { true => "fxa auth_profile ${::env}", default => '' }})
```

**Comment by philbooth** [comment]
I've proposed a change to the `config` crate that would make this behave as you expect.

Ref: mehcode/config-rs#78

**Comment by jrgm** [comment]
Thanks @philbooth!
