### ISSUE TITLE
Write tests for the SES provider

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-email-service#21]
Currently the tests all use the `mock` provider. We should figure out how to mock the framework around Rusoto and then write tests that exercise the `ses` provider too.

**Comment by brizental** [comment]
I was thinking about which tests we need here, I'm not really sure about it so, these are the ones I came up with, if you think we need more than these or if they are completely wrong, lmk.

- Check that RawMessage is created correctly for these cases:
   - with | without headers
   - cc.len() > 0 | cc.len() < 0

**Comment by philbooth** [comment]
@brizental, that sounds about right to me!
