### ISSUE TITLE
Convert string settings types to enums where possible

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-email-service#216]
The following types all have a limited set of values and should probably modelled as enums rather than strings:

* [ ] ~~`settings::AwsRegion`~~
* [x] `settings::DefaultProvider`
* [x] `settings::Env`
* [x] `settings::LoggingLevel`
* [x] `settings::LoggingFormat`

**Comment by philbooth** [comment]
> `settings::DefaultProvider`

Ref: #218

**Comment by vladikoff** [comment]
from mtg: @philbooth still 126?

**Comment by philbooth** [comment]
> * [ ] `settings::AwsRegion`

Correction, let's just use [`rusoto_core::Region`](https://rusoto.github.io/rusoto/rusoto_core/region/enum.Region.html) for that one instead.
