### ISSUE TITLE
Provision an SQS queue for email service => auth server communication

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-email-service#219]
* Name: `fxa-email-notification-{dev|stage|prod}`
* Related: mozilla/fxa-auth-server#2684

**Comment by philbooth** [comment]
Pulled across to `active` to be done as part of the train 125 deployment cycle. Note this is an ops task, so there's no need to freak out about the fact I'm on PTO and my face is on this.

**Comment by vladikoff** [comment]
from mtg: jrgm will have a PR for this

**Comment by jrgm** [comment]
This was done in the train-125 release today (https://bugzilla.mozilla.org/show_bug.cgi?id=1507023) - https://github.com/mozilla-services/cloudops-deployment/pull/2768
