### ISSUE TITLE
Sentry errors in SesProvider::send

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-email-service#220]
Our first Sentry error for this repo! :tada:

https://sentry.prod.mozaws.net/operations/email-service/issues/4900545/?environment=release

Backtrace:

```
    <unknown>0x55f030cf6792<backtrace::capture::Backtrace as core::default::Default>::default
    Called from: backtracebacktrace::capture::Backtrace::new
    <unknown>0x55f0307f8c37<std::thread::local::LocalKey<T>>::with
    Called from: sentrysentry::hub::Hub::with_active
    <unknown>0x55f030dfa265rust_begin_unwind panicking.rs:325
    Called from: corecore::panicking::panic_fmt panicking.rs:77
    <unknown>0x55f030e485d6<core::result::Result<T, E>>::expect result.rs:809
    Called from: allocalloc::fmt::format fmt.rs:570
    <unknown>0x55f0306f9cee<fxa_email_service::providers::ses::SesProvider as fxa_email_service::providers::Provider>::send
    fxa_email_service0x55f0306dcd00fxa_email_service::providers::Providers::send
    fxa_email_service0x55f03075d60bfxa_email_service::send::handler
    fxa_email_service0x55f03075d0e9fxa_email_service::send::rocket_route_fn_handler
    rocket0x55f030b40b50rocket::rocket::Rocket::route_and_process
    <unknown>0x55f030b3ec88<rocket::rocket::Rocket as hyper::server::Handler>::handle
    <unknown>0x55f030b2e90a<hyper::server::Worker<H>>::handle_connection
    hyper0x55f030b45fa7hyper::server::listener::spawn_with::{{closure}}
    Called from: stdstd::sys_common::backtrace::__rust_begin_short_backtrace
    <unknown>0x55f030b1d8d2<F as alloc::boxed::FnBox<A>>::call_box
    <unknown>0x55f030dfc48a<alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once boxed.rs:652
    Called from: stdstd::sys_common::thread::start_thread thread.rs:24
    <unknown>0x7fa09b6bb493start_thread
    <unknown>0x7fa09b1e6ace__clone
    <unknown>0x000000000000<unknown> 
```

**Comment by philbooth** [comment]
This is the offending code:

```rust
let message =
    build_multipart_mime(&self.sender, to, cc, headers, subject, body_text, body_html)?;
let encoded_message = encode(&format!("{}", message));
let mut request = SendRawEmailRequest::default();
request.raw_message = RawMessage {
    data: format!("{}", encoded_message).as_bytes().to_vec(),
};
```

**Comment by philbooth** [comment]
And a couple of hours later there's another, maybe-related, slightly different error in the same function:

```
HttpDispatch(HttpDispatchError { message: "parsed HTTP message from remote is incomplete" })
    fxa_email_service0x55b29a06af3bfxa_email_service::providers::ses::<impl core::convert::From<rusoto_ses::generated::SendRawEmailError> for fxa_email_service::app_errors::AppError>::from
    <unknown>0x55b29a00cf88<fxa_email_service::providers::ses::SesProvider as fxa_email_service::providers::Provider>::send
    fxa_email_service0x55b299fefd00fxa_email_service::providers::Providers::send
    fxa_email_service0x55b29a07060bfxa_email_service::send::handler
    fxa_email_service0x55b29a0700e9fxa_email_service::send::rocket_route_fn_handler
    rocket0x55b29a453b50rocket::rocket::Rocket::route_and_process
    <unknown>0x55b29a451c88<rocket::rocket::Rocket as hyper::server::Handler>::handle
    <unknown>0x55b29a44190a<hyper::server::Worker<H>>::handle_connection
    hyper0x55b29a458fa7hyper::server::listener::spawn_with::{{closure}}
    Called from: stdstd::sys_common::backtrace::__rust_begin_short_backtrace
    <unknown>0x55b29a4308d2<F as alloc::boxed::FnBox<A>>::call_box
    <unknown>0x55b29a70f48a<alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once boxed.rs:652
    Called from: stdstd::sys::unix::thread::Thread::new::thread_start thread.rs:90
    <unknown>0x7fefd3386493start_thread
    <unknown>0x7fefd2eb1ace__clone
    <unknown>0x000000000000<unknown> 
```

**Comment by jrgm** [comment]
So, yeah, I had some traffic set to go via the email-service starting this afternoon PDT, and I shut it down a bit over an hour ago.

I'm confused about your comment 'And a couple of hours later...'. 

The sentry error noted in the first comment says it has timestamp of 'Nov 1, 2018 5:14:34 AM UTC'. Which is about 75 minutes ago. (Curiously almost the same time I stopped routing traffic to it. hmm).

**Comment by philbooth** [comment]
My bad, I was looking at the timestamps in my email, not the ones in Sentry itself.

**Comment by jrgm** [comment]
I should have been watching Sentry. My mistakes. But SES stats looked nominal during the time this was active. Is this on an an error handling path when SES rejects?

**Comment by philbooth** [comment]
> Is this on an an error handling path when SES rejects?

The error in the first comment occurs before anything reaches SES, when we're constructing the message payload.

The other error seems to be that Rusoto is complaining about the response payload it receives, so it's possible that it comes from a non-error path on the SES side of things.

**Comment by philbooth** [comment]
Focusing on the first error mentioned, because that had 155 occurrences (versus 3 of the second error), I've not been able to reproduce it locally yet having tried all the main flows sending email via the email service. Maybe it is specific to certain message payloads.

One thing I noticed is that the mime-encoding crate we're using looks very new and there is a more battle-hardened option available. I might patch the train-124 branch to use that instead.

**Comment by philbooth** [comment]
> the mime-encoding crate we're using looks very new

(also, it doesn't have any tests 😱)

**Comment by philbooth** [comment]
I have a couple of "fixes" lined up for this, "fixes" because I haven't been able to reproduce locally so am only speculating about the root cause.

The first "fix" is to skip the intermediate string step during mime encoding, for which I have a branch [here](https://github.com/mozilla/fxa-email-service/compare/train-124...pb/mime-encoding). It almost works, but the email body is sent as an attachment rather than inline. I think that might be related to an issue I'm discussing in the `emailmessage` crate, [here](https://github.com/katyo/emailmessage-rs/issues/1).

The second "fix" is to use something different to the `emailmessage` crate. I'm playing about with the `mime-multipart` crate to this end and may PR that depending on what happens with the other thing.

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-email-service/pull/228 landed, closing, but feel free to reopen if we want to wait to see if that resolves the issue
