### ISSUE TITLE
Include debug symbols for more detailed Sentry errors

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-email-service#222]
Noticed [this](https://blog.sentry.io/2018/05/01/sentry-for-rust):

> Errors will contain as much information as possible at event submission, so the most important step is to make sure to ship your debug information in the executable. Experimental support for server side symbolication is also provided if you upload debug symbols.

Currently we're not including debug symbols in the release build. We can do that by setting `debug = true` in the `[profile.release]` section of Cargo.toml.

**Comment by vladikoff** [comment]
👍
