### ISSUE TITLE
Set rocket config for stage and prod

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-email-service#24]
There is a config file for Rocket in the root directory, `Rocket.toml`. Most of the stuff in there is pretty standard, address and port to listen on, etc. You can read more about it at:

https://api.rocket.rs/rocket/config/

One that stands out as interesting for prod is `workers` / `ROCKET_WORKERS`, which defines how many worker threads Rocket should create for handling requests. The default value is CPU count * 2. We'll probably need to do some testing to zero in on the optimal value for that, especially given that it will be sharing a box with auth server and auth db processes.

**Comment by vladikoff** [comment]
@brizental Could you take a look at this for this train.

I think we need to make sure to tell DevOps to run the app with

ROCKET_ENV=production 

(plus stage support as well)


and have the following configs added based on the doc link above:

address = "127.0.0.1"
port = "8001"

Probably the same for both prod and stage. I wouldn't worry about the `workers` settings for now.
