### ISSUE TITLE
Refactor settings properties to types

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-email-service#25]
We had some problems with the `config` crate, making it deserialize to our own types. You can see some of the hoops we had to jump through to make that work in the unmerged PR, #14.

At some point we should loop back round to see if we can resolve those issues. It would be nice to decentralise all the `validate` and `deserialize` stuff back to `Deserialize`-implementing type modules and then get rid of those two entirely. We'd also be able to lose the the `deserialize_with = ...` stuff in the `Settings` module.

**Comment by brizental** [comment]
Hey Phil, can you explain this issue a littler further to me? 

I was studying serde and I think I could help with this issue, but since I wasn't following the project when you filed it I think I might need some more info.

**Comment by vladikoff** [comment]
@brizental do 1 or 2 and send a PR to check to make sure we are on the right track....
