### ISSUE TITLE
Store extra data associated with a request and propagate it on outgoing notifications

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-email-service#4]
Synchronised in the sense that duplicate ids must never occur across peer instances. Should be returned in `200` responses from `/send` as `messageId` and included in any delivery/bounce/complaint messages.

**Comment by philbooth** [comment]
I've been weighing up some options for this, trying to focus on which will turn out to be the correct long-term bet for what we want this service to morph into.

Before getting into what the options actually are, these are the requirements as I see them:

* In the short-term, we want to store a small amount of data that lives for the duration until a message is removed from the bounce/complaint/delivery queue. It must be possible to look up that data using the provider-specific message id that we receive from the queues. The concrete use-case I'm thinking of here is so that the auth server can propagate its metrics context in outgoing notifications without having to use its own storage layer.

* Medium-term, we want to migrate away from the auth db for bounce records so that we're not coupled with the auth server any more.

* Long-term, we will probably also want more permanent storage of caller-specific configuration options such as the outgoing queue to use for notifications (see #38).

As I see it, there are two variables at play in the decision:

1. What data store should we use?

2. What should the message id look like?

In answer to `1`, Redis seems like a pretty good choice for the short-term case. The medium- and long-term cases introduce different data types and at least one relationship to be modelled (mapping a message id to an outgoing queue). Redis could be extended to those cases if we use separately-prefixed keys for the different data "types" and don't auto-evict old data, but I feel like we might be better off including a full-blown SQL schema at that point. But we don't have to resolve that question now, I think it's fine to start off with Redis and cross the other bridge when we get to it.

Question `2` is more interesting I think. Obviously if we need to look up the data using the provider-specific id, then the Redis key should be based on that. But we probably don't want that to be a message id we return to callers, as it leaks implementation details we don't want them to know about. So we can either use a hash of the provider-specific id, or make it random and store it in Redis keyed by the provider-specific id. The former seems preferable because it keeps the data smaller, is deterministic for better testing and, in future, may let us avoid writing to Redis at all (if the caller hasn't specified any extra data to be propagated in the notification).

So at that point, I'm wondering why even bother returning the caller a message id at all? Originally I planned to do it because I envisaged the auth server being responsible for storing its metrics context, and it would use the message id to fetch metrics context when it receives a notification. But that feels like a heavy cost to impose on callers, which could easily be done internally here (and to be fair, @rfk did suggest this in the feature doc when we wrote it, it's just taken a while to filter through my skull I guess). If we're not publishing any APIs that accept a message id, we've got no business returning it to them.

But but but... if we're not returning the message id to callers then, why are we bothering to hash it in Redis? We could just use the provider-specific id, namespaced with `ses:...` or `sendgrid:...`, as the code does now. This would be simpler and make the Redis data potentially more useful when debugging, if you wanted to manually look up a message for some reason. Hence I have gone full circle and think maybe we don't want to generate a synchronised message id at all.

**Comment by rfk** [comment]
One consideration for the future may be an API that allows the caller to query the status of a send, basically to pass us the message id and ask us what's up with that message.  We might reply that it's still pending, or was delivered successfully, or bounced or whatever.

But it seems safe to address the "how does the caller identify a message" question later on, if and when we actually cone to grapple with such an API.  So 👍 to the short-term focus here.

> make the Redis data potentially more useful when debugging

One additional consideration for this data is that it may be fairly security-sensitive, e.g. containing secret codes designed for email verification, or containing PII.  I don't know if that really changes how we'd deal with it in any way, but it's worth keeping in mind explicitly.  (For comparison, IIUC we deliberately *don't* store any security-sensitive things in the device metadata that the auth-server writes into redis).
