### ISSUE TITLE
Use failure crate for error handling

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-email-service#48]
Recommendation from the push team. Example usage in [mozilla-services/megaphone](https://github.com/mozilla-services/megaphone) and [mozilla-services/pushbox](https://github.com/mozilla-services/pushbox).

**Comment by philbooth** [comment]
(alternative recommendation was `error_chain`, but it sounds like `failure` is what the cool kids are using)

**Comment by vladikoff** [comment]
@philbooth assigned to @brizental, she spent some time looking into error handling while working on the Logging PR

**Comment by brizental** [comment]
I'll start looking at this now. I had a look at the megaphone error handling code and I think we can actually reuse a lot of their code to try this out.
