### ISSUE TITLE
Inject config rather than statically initialising

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-email-service#49]
Statically initialising config makes it hard to test (as we've already discovered). Recommendation from the push folks is to inject it everywhere we need it, so that tests can properly interrogate what's going on.

**Comment by philbooth** [comment]
(and then we can get rid of that rubbish `CleanEnvironment` hack I did)

**Comment by philbooth** [comment]
(and also stop running the tests in a single thread)

**Comment by brizental** [comment]
I'll work on this :) It's necessary to make the settings logging better.
