### ISSUE TITLE
Start redis or warn when running `./tdb`?

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-email-service#84]
I saw a redis panic when running `./tdb`. Should we start redis or print out a message that redis is not available and should be running when we run those tests?

**Comment by philbooth** [comment]
If we can start it nicely cross-platform I'm in favour of doing that. If not a sensible log message is definitely a good start, yep.

**Comment by vladikoff** [comment]
Seems like we are okay without this for now, closing until needed
