### ISSUE TITLE
Ensure unicode handling is sane

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-email-service#9]
Depends on #21. Write tests for unicode characters and make sure they pass.

**Comment by philbooth** [comment]
Part of this will include setting `charset` in `src/providers/ses.rs`, as per https://github.com/mozilla/fxa-email-service/pull/17#discussion_r186314207.

**Comment by philbooth** [comment]
Was going to pick this up then I realised there's not much we can do until we have better tests for SES/Sendgrid. Will come back to it.

**Comment by brizental** [comment]
@philbooth hey, Phil! I'm want to start working on this, can you just explain it to me a little further so that I understand it completely?

**Comment by vladikoff** [comment]
@philbooth should we grab the unicode test cases from the fxa-auth-server? any others?

**Comment by philbooth** [comment]
Yep, there might not be much to it tbh. Essentially all I was thinking was that we don't have any tests that fire unicode characters through our providers yet. Maybe everything is fine, or maybe it isn't.

So at the very least we want a test in `src/send/test.rs` that fires a selection of unicode characters through some of the params to the mock provider. Ideally we'd also have something that stress-tests SES too via the mock SES stuff you did. Then if the new tests pass there's nothing more to do than that!

Make sure you pick some unicode characters from the higher planes, so that we're throwing multi-byte input at it. (the 🦀 emoji might be appropriate there!)

And make sure all the params are covered of course.

**Comment by philbooth** [comment]
> should we grab the unicode test cases from the fxa-auth-server?

Didn't know there were any! If there's some we can re-use then yep!

**Comment by brizental** [comment]
Just documenting my findings here, I think we are actually not able to handle unicode character the way we do things now. I tried this test and it failed: 

```
fn unicode_email_field() {
    let client = setup();

    let random_unicode_string :String = (0..10).map(|_| random::<char>()).collect();
    // let random_unicode_string = String::from("一丁丂七丄丅丆万丈三上");
    let mut response = client
        .post("/send")
        .header(ContentType::JSON)
        .body(format!("{{
            \"to\": [ \"{}@example.com\" ],
            \"cc\": [ \"bar\" ],
            \"subject\": \"baz\",
            \"body\": {{
                \"text\": \"qux\"
            }},
            \"provider\": \"mock\"
        }}", random_unicode_string))
        .dispatch();

    assert_eq!(response.status(), Status::Ok);

    let body = response.body().unwrap().into_string().unwrap();
    assert_eq!(body, json!({ "messageId": "mock:deadbeef" }).to_string());
}
```

This also failed: 

```
curl \                  
  -d '{"to":"一丁丂七丄丅丆万丈三上@example.com","subject":"bar","body":{"text":"baz"}, "provider":"ses"}' \
  -H 'Content-Type: application/json' \
  http://localhost:8001/send
```

Both times I got parsing errors. If anyone has any idea what's going on or if you see that I'm doing something wrong in the test cases, let me know. I'll keep digging on this meanwhile :)

**Comment by philbooth** [comment]
@brizental, I notice that you're setting the data in the `to` field. That param is validated by a regex, do you also need to update that regex to let your data through?

**Comment by philbooth** [comment]
(or maybe just test in the other fields, it's not clear to me whether we need to validate unicode email addresses or not right now, how do the content/auth servers validate email addresses?)

**Comment by brizental** [comment]
@philbooth Yes, the problem is with the Regex... So, auth server checks for unicode email addresses that's why I added that test (https://github.com/mozilla/fxa-auth-server/blob/63738c85b5443c7e15bc03610deec9f1223e03eb/test/remote/account_create_tests.js#L392). Just added the tests for all the fields that are not emails and they work fine :)

**Comment by shane-tomlinson** [comment]
> Cool, let's update the regex in that case!

If the auth-server allows unicode in the email address, the [content server probably should too](https://github.com/mozilla/fxa-content-server/blob/61c627bff21167b18686a507415848fa03df528b/app/scripts/lib/validate.js#L43).
